config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: "restaurants#index" 
  get "restaurants", to: "restaurants#index"
  get "restaurants/:id", to: "restaurants#show", as: :resto_show

  # EDIT / UPDATE
  get "restaurants/new", to: "restaurants#new"
  post "restaurants", to: "restauransts#create"

  # Appliquer
  # resources :restaurants, except: :index do
  # resources :reviews, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = ["chinese", "italian", "japanese", "french", "belgian"]
  
  validates :name, presence: true
  validates :address, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  validates :rating, presence: true, inclusion: { in: 0..5 }, numericality: true
  validates :content, presence: true
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end
  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end
  def new
    @restaurant = Restaurant.new
  end
  def create
    @restaurant = Restaurant.find(params[:id])
    @restaurants.save
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>List of Restaurants</h1>

<% @restaurants.each do |r| %>
<div class="card m-5" style="width: 18rem;">
  <img src="https://media-cdn.tripadvisor.com/media/photo-s/1a/f6/04/87/image-restaurant.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title"><%= r.name %></h5>
    <p class="card-text">Some text</p>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%= r.address %></li>
    <li class="list-group-item"><%= r.phone_number %></li>
    <li class="list-group-item"><%= r.category %></li>
  </ul>
  <div class="card-body">
    <%= link_to "View", resto_show_path(r.id), class: "card-link" %>
    <a href="#" class="card-link">Delete</a>
  </div>
</div>
<% end %>

app/views/restaurants/show.html.erb
<h1>Restaurant's details</h1>

<% simple_form_for [@restaurant, @review] do |f| %>
  <% f.input :name %>
  <% f.submit "Create" %>
<% end %>
  

<%= link_to "Back", restaurants_path, class: "card-link" %>